blank_issues_enabled: false
contact_links:
  - name: Question or Discussion
    url: https://github.com/orgs/community/discussions
    about: For questions or discussions that aren't actionable issues
